### ISSUE TITLE
Running `npm start` hangs and localhost:8080 doesn't load

### ISSUE THREAD

**Issue by fourcolors** [hmmhmmhm/svelte-template#3]
When doing a straight git clone I'm having trouble loading `localhost:8080` 

Steps:

`npm install`
`npm start`

Is there anything else that needs to be done? I've also `.gitignore`ed `node_modules` and the `.cache`

**Comment by hmmhmmhm** [comment]
Hi!, I hope you have a good Christmas!

I usually use Mac, but I just did a
more test in Windows 10 x64 system.

![12](https://user-images.githubusercontent.com/38493722/71433245-5283e100-2721-11ea-809c-13bfb679cf1f.png)

In my environment, the installation
seems to be proceeding normally.

I was told that this template was not working properly
in some environments, and I think it was mostly a Windows environment.
If I have time next time, I will add more manuals for various os users.

Also It is recommended that the node js are installed up to date
and that the chocolates provided for the windows during installation are not omitted.

If you have any other problems, please let me know and I can help you.

**Comment by fourcolors** [comment]
Thanks! Merry Christmas to you too,

I'm working in Fish on a Mac as well, I'm not sure if that had anything to do with it. After re-installing `node_modules` everything seems to run smoothly however I found I needed to wait for the server to fully run before going to `localhost:8080` refreshing early seemed to make the server hang.
