### ISSUE TITLE
npm install results to  'rm' ist not recoqnized

### ISSUE THREAD

**Issue by Jarmo-Baltzar** [hmmhmmhm/svelte-template#5]
After cloning git and then running npm install results to error.
 rm -rf ./.cache && node ./postinstall.ts

'rm' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-spa-template@1.0.3 postinstall: `rm -rf ./.cache && node ./postinstall.ts`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the svelte-spa-template@1.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jarmo\AppData\Roaming\npm-cache\_logs\2020-02-23T11_42_29_088Z-debug.log

**Comment by hmmhmmhm** [comment]
The commands of this project are optimized for the bash environment.
If you use windows, it is recommended to use git-bash.
https://gitforwindows.org/

**Comment by Jarmo-Baltzar** [comment]
Brilliant .. it works .. Thank you !
